//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.UI.Views {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Texte {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texte() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERP.UI.Views.Texte", typeof(Texte).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Abbrechen {
            get {
                return ResourceManager.GetString("Abbrechen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        public static string Abmelden {
            get {
                return ResourceManager.GetString("Abmelden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All windows will be closed. Are you sure? ähnelt.
        /// </summary>
        public static string AllesSchließenFrage {
            get {
                return ResourceManager.GetString("AllesSchließenFrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string Anmelden {
            get {
                return ResourceManager.GetString("Anmelden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Have an account? ähnelt.
        /// </summary>
        public static string AnmeldenFrage {
            get {
                return ResourceManager.GetString("AnmeldenFrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid email or password. Please check and try again ähnelt.
        /// </summary>
        public static string AnmeldungFehler {
            get {
                return ResourceManager.GetString("AnmeldungFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        public static string AnmeldungTitel {
            get {
                return ResourceManager.GetString("AnmeldungTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string Anzeigen {
            get {
                return ResourceManager.GetString("Anzeigen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ERP.UI ähnelt.
        /// </summary>
        public static string AppTitel {
            get {
                return ResourceManager.GetString("AppTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User ähnelt.
        /// </summary>
        public static string Benutzer {
            get {
                return ResourceManager.GetString("Benutzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Benutzername {
            get {
                return ResourceManager.GetString("Benutzername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        public static string BestätigePasswort {
            get {
                return ResourceManager.GetString("BestätigePasswort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Orders ähnelt.
        /// </summary>
        public static string Bestellungen {
            get {
                return ResourceManager.GetString("Bestellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string Dunkel {
            get {
                return ResourceManager.GetString("Dunkel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Einstellungen {
            get {
                return ResourceManager.GetString("Einstellungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die E-mail ähnelt.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid email address. ähnelt.
        /// </summary>
        public static string EmailFehlt {
            get {
                return ResourceManager.GetString("EmailFehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The entered email address has an invalid format. ähnelt.
        /// </summary>
        public static string EmailNichtGültig {
            get {
                return ResourceManager.GetString("EmailNichtGültig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a name with at least 3 letters. ähnelt.
        /// </summary>
        public static string FehlerName {
            get {
                return ResourceManager.GetString("FehlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main Menu ähnelt.
        /// </summary>
        public static string HauptMenü {
            get {
                return ResourceManager.GetString("HauptMenü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string Hell {
            get {
                return ResourceManager.GetString("Hell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Ja {
            get {
                return ResourceManager.GetString("Ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customers ähnelt.
        /// </summary>
        public static string Kunden {
            get {
                return ResourceManager.GetString("Kunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name cannot contain white spaces. ähnelt.
        /// </summary>
        public static string NameFehler {
            get {
                return ResourceManager.GetString("NameFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string Nein {
            get {
                return ResourceManager.GetString("Nein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data for New Task Missing! Please provide all necessary data to add a new task. ähnelt.
        /// </summary>
        public static string NeueAufgabeFehler {
            get {
                return ResourceManager.GetString("NeueAufgabeFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter task day. ähnelt.
        /// </summary>
        public static string NeueAufgabeTag {
            get {
                return ResourceManager.GetString("NeueAufgabeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a description of your next task. ähnelt.
        /// </summary>
        public static string NeueAufgabeTipp {
            get {
                return ResourceManager.GetString("NeueAufgabeTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide a name for the new group! ähnelt.
        /// </summary>
        public static string NeueGruppeFehler {
            get {
                return ResourceManager.GetString("NeueGruppeFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a name for the new group. ähnelt.
        /// </summary>
        public static string NeueGruppeTipp {
            get {
                return ResourceManager.GetString("NeueGruppeTipp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Window ähnelt.
        /// </summary>
        public static string NeuesFenster {
            get {
                return ResourceManager.GetString("NeuesFenster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Passwort {
            get {
                return ResourceManager.GetString("Passwort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The passwords do not match. Please check your input. ähnelt.
        /// </summary>
        public static string PasswortFehler {
            get {
                return ResourceManager.GetString("PasswortFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a password. The password must be 8 characters long. ähnelt.
        /// </summary>
        public static string PasswortFehlt {
            get {
                return ResourceManager.GetString("PasswortFehlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Products ähnelt.
        /// </summary>
        public static string Produkte {
            get {
                return ResourceManager.GetString("Produkte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invoices ähnelt.
        /// </summary>
        public static string Rechnungen {
            get {
                return ResourceManager.GetString("Rechnungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Registrieren {
            get {
                return ResourceManager.GetString("Registrieren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Don&apos;t have an account? ähnelt.
        /// </summary>
        public static string RegistrierenFrage {
            get {
                return ResourceManager.GetString("RegistrierenFrage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Account ähnelt.
        /// </summary>
        public static string RegistrierenTitel {
            get {
                return ResourceManager.GetString("RegistrierenTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You need to be online to register a new account. ähnelt.
        /// </summary>
        public static string RegistrierenWarnung {
            get {
                return ResourceManager.GetString("RegistrierenWarnung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration successful! Would you like to log in now? ähnelt.
        /// </summary>
        public static string RegistrierungErfolgreich {
            get {
                return ResourceManager.GetString("RegistrierungErfolgreich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registration unsuccessful. It seems that the provided email is already associated with an account. Please try logging in or use a different email to register. ähnelt.
        /// </summary>
        public static string RegistrierungFehler {
            get {
                return ResourceManager.GetString("RegistrierungFehler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your access key has expired. Please login in again. ähnelt.
        /// </summary>
        public static string SchlüsselAbgelaufen {
            get {
                return ResourceManager.GetString("SchlüsselAbgelaufen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Language ähnelt.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Sprachen {
            get {
                return ResourceManager.GetString("Sprachen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please restart the application to take the new language! ähnelt.
        /// </summary>
        public static string Sprachwechsel {
            get {
                return ResourceManager.GetString("Sprachwechsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Startseite {
            get {
                return ResourceManager.GetString("Startseite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Themes ähnelt.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Theme ähnelt.
        /// </summary>
        public static string Themewechseln {
            get {
                return ResourceManager.GetString("Themewechseln", resourceCulture);
            }
        }
    }
}
